import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import { collection, addDoc, getDocs, query } from 'firebase/firestore';
import { db } from './api/firebase-config';



export default function Home() {
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [message, setMessage] = useState('');
  const [details, setDetails] = useState([]);

  useEffect(() => {
    userData();
  }, []);

  const handleClick = async () => {
    try {
      const docRef = await addDoc(collection(db, "users"), {
        firstName,
        lastName,
        message
      });
      console.log('Document written with ID: ', docRef.id);
    } catch (e) {
      console.error("Error adding document: ", e);
    }
  };

  const userData = async () => {
    const q = query(collection(db, "users"));

    const querySnapshot = await getDocs(q);
    const data = querySnapshot.docs.map((doc) => ({
      ...doc.data(),
      id: doc.id
    }));
    setDetails(data);
  };
  console.log(details);


  return (
    <div className={styles.container}>
      <Head>
        <title>next-firestore-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>next-firestore-app</h1>

      <input type='text' placeholder='First Name' onChange={(e) => setFirstName(e.target.value)} />
      <input type='text' placeholder='Last Name' onChange={(e) => setLastName(e.target.value)} />
      <input type='text' placeholder='Message' onChange={(e) => setMessage(e.target.value)} />
      <button onClick={handleClick}>Send!</button>
      {details.map((val, id) => {
        return (
          <p key={id}>{val.firstName} says: {val.message}</p>
        );
      })}
    </div>
  );
}
